export const TOOLS = [
  {
    id: "what-should-i-eat",
    name: "What Should I Eat?",
    description: "Spin a wheel to pick your next meal. Filter by dietary preferences.",
    category: "Decision Making",
    path: "/what-should-i-eat",
    icon: "Utensils",
    color: "bg-orange-500",
  },
  {
    id: "what-should-i-watch",
    name: "What Should I Watch?",
    description: "Random movie or show picker with genre filters.",
    category: "Decision Making",
    path: "/what-should-i-watch",
    icon: "Tv",
    color: "bg-blue-500",
  },
  {
    id: "random-decision-maker",
    name: "Random Decision Maker",
    description: "Type your options and let fate decide the winner.",
    category: "Decision Making",
    path: "/random-decision-maker",
    icon: "Dices",
    color: "bg-purple-500",
  },
  {
    id: "yes-or-no-generator",
    name: "Yes or No Generator",
    description: "Flip a coin visually for an instant yes or no answer.",
    category: "Decision Making",
    path: "/yes-or-no-generator",
    icon: "HelpCircle",
    color: "bg-pink-500",
  },
  {
    id: "choice-picker",
    name: "Choice Picker",
    description: "Paste a list of choices and pick one randomly.",
    category: "Decision Making",
    path: "/choice-picker",
    icon: "ListChecks",
    color: "bg-indigo-500",
  },
  {
    id: "random-restaurant-picker",
    name: "Random Restaurant Picker",
    description: "Type your area and let us randomly pick a great restaurant for you.",
    category: "Decision Making",
    path: "/random-restaurant-picker",
    icon: "MapPin",
    color: "bg-amber-500",
  },
  {
    id: "calorie-estimator",
    name: "Calorie Estimator",
    description: "Type any food or drink and instantly get its calorie count.",
    category: "Decision Making",
    path: "/calorie-estimator",
    icon: "Flame",
    color: "bg-red-500",
  },
  {
    id: "truth-or-dare",
    name: "Truth or Dare",
    description: "Random truths and dares with intensity filters.",
    category: "Fun & Social",
    path: "/truth-or-dare",
    icon: "Smile",
    color: "bg-red-500",
  },
  {
    id: "never-have-i-ever",
    name: "Never Have I Ever",
    description: "Fun prompts for your next party game.",
    category: "Fun & Social",
    path: "/never-have-i-ever",
    icon: "MessageCircle",
    color: "bg-yellow-500",
  },
  {
    id: "challenge-generator",
    name: "Challenge Generator",
    description: "Random fun challenges to do solo or with friends.",
    category: "Fun & Social",
    path: "/challenge-generator",
    icon: "Swords",
    color: "bg-green-500",
  },
  {
    id: "would-you-rather",
    name: "Would You Rather",
    description: "Tough dilemmas to choose between, with live voting stats.",
    category: "Fun & Social",
    path: "/would-you-rather",
    icon: "SplitSquareHorizontal",
    color: "bg-teal-500",
  },
  {
    id: "gen-z-slang-generator",
    name: "Gen Z Slang Generator",
    description: "Learn a random slang term with its definition and usage.",
    category: "Fun & Social",
    path: "/gen-z-slang-generator",
    icon: "Zap",
    color: "bg-cyan-500",
  },
  {
    id: "most-likely-to",
    name: "Most Likely To",
    description: "Generate random 'Most Likely To' questions for groups and parties.",
    category: "Fun & Social",
    path: "/most-likely-to",
    icon: "Users",
    color: "bg-indigo-500",
  },
  {
    id: "friendship-quiz",
    name: "Friendship Quiz",
    description: "Answer 10 questions and discover your friendship archetype.",
    category: "Fun & Social",
    path: "/friendship-quiz",
    icon: "HeartHandshake",
    color: "bg-pink-500",
  },
  {
    id: "who-knows-me-better",
    name: "Who Knows Me Better?",
    description: "Create a personal quiz and test which friend knows you best.",
    category: "Fun & Social",
    path: "/who-knows-me-better",
    icon: "Users2",
    color: "bg-teal-500",
  },
  {
    id: "dice-roller",
    name: "Dice Roller",
    description: "Roll 1, 2, or 3 dice with realistic animations. Perfect for any game.",
    category: "Fun & Social",
    path: "/dice-roller",
    icon: "Dices",
    color: "bg-green-500",
  },
  {
    id: "random-song-generator",
    name: "Random Song Generator",
    description: "Pick a language and mood — get a popular song recommendation.",
    category: "Fun & Social",
    path: "/random-song-generator",
    icon: "Music",
    color: "bg-purple-500",
  },
  {
    id: "would-you-survive",
    name: "Would You Survive?",
    description: "Zombie apocalypse, Titanic, Mars mission — find out if you'd make it.",
    category: "Fun & Social",
    path: "/would-you-survive",
    icon: "Shield",
    color: "bg-green-600",
  },
  {
    id: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your weighted GPA easily.",
    category: "Student Tools",
    path: "/gpa-calculator",
    icon: "GraduationCap",
    color: "bg-sky-500",
  },
  {
    id: "study-planner",
    name: "Study Planner",
    description: "Plan and visualize your weekly study sessions.",
    category: "Student Tools",
    path: "/study-planner",
    icon: "Calendar",
    color: "bg-violet-500",
  },
  {
    id: "exam-countdown",
    name: "Exam Countdown",
    description: "Track days, hours, and minutes until your big tests.",
    category: "Student Tools",
    path: "/exam-countdown",
    icon: "Timer",
    color: "bg-rose-500",
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Quickly solve common percentage math problems.",
    category: "Student Tools",
    path: "/percentage-calculator",
    icon: "Percent",
    color: "bg-emerald-500",
  },
  {
    id: "attendance-calculator",
    name: "Attendance Calculator",
    description: "Check your attendance %, how many classes you can skip safely.",
    category: "Student Tools",
    path: "/attendance-calculator",
    icon: "CheckCircle",
    color: "bg-blue-500",
  },
  {
    id: "cgpa-calculator",
    name: "CGPA Calculator",
    description: "Calculate your cumulative GPA across semesters on any scale.",
    category: "Student Tools",
    path: "/cgpa-calculator",
    icon: "GraduationCap",
    color: "bg-violet-600",
  },
  {
    id: "marks-predictor",
    name: "Marks Predictor",
    description: "Predict your final percentage and know what you need to score.",
    category: "Student Tools",
    path: "/marks-predictor",
    icon: "TrendingUp",
    color: "bg-emerald-600",
  },
  {
    id: "revision-scheduler",
    name: "Revision Scheduler",
    description: "Get a spaced repetition revision schedule before your exam.",
    category: "Student Tools",
    path: "/revision-scheduler",
    icon: "BookOpen",
    color: "bg-sky-600",
  },
  {
    id: "todo-list-generator",
    name: "To-Do List Generator",
    description: "Type your goal and get an instant actionable checklist.",
    category: "Productivity",
    path: "/todo-list-generator",
    icon: "ListChecks",
    color: "bg-amber-500",
  },
  {
    id: "habit-tracker",
    name: "Habit Tracker",
    description: "Track daily habits, build streaks, and stay consistent.",
    category: "Productivity",
    path: "/habit-tracker",
    icon: "Flame",
    color: "bg-orange-500",
  },
  {
    id: "time-blocking-planner",
    name: "Time Blocking Planner",
    description: "Turn your task list into a color-coded daily schedule.",
    category: "Productivity",
    path: "/time-blocking-planner",
    icon: "Clock",
    color: "bg-blue-500",
  },
  {
    id: "morning-routine-planner",
    name: "Morning Routine Planner",
    description: "Build your perfect morning routine with a timed schedule.",
    category: "Productivity",
    path: "/morning-routine-planner",
    icon: "Sunrise",
    color: "bg-yellow-500",
  },
  {
    id: "water-reminder",
    name: "Water Reminder",
    description: "Track your daily water intake and hit your hydration goal.",
    category: "Productivity",
    path: "/water-reminder",
    icon: "Droplets",
    color: "bg-cyan-500",
  },
  {
    id: "excuse-generator",
    name: "Excuse Generator",
    description: "Get the perfect excuse for any situation — believable, funny, or genius.",
    category: "Productivity",
    path: "/excuse-generator",
    icon: "MessageSquare",
    color: "bg-amber-600",
  },
  {
    id: "future-self-letter",
    name: "Future Self Letter",
    description: "Answer a few questions and get a heartfelt letter from your future self.",
    category: "Productivity",
    path: "/future-self-letter",
    icon: "Mail",
    color: "bg-indigo-500",
  },
  {
    id: "love-percentage-calculator",
    name: "Love Percentage Calculator",
    description: "Enter two names and discover your love score and match type.",
    category: "Love & Relationships",
    path: "/love-percentage-calculator",
    icon: "Sparkles",
    color: "bg-pink-500",
  },
  {
    id: "date-idea-generator",
    name: "Date Idea Generator",
    description: "Pick budget and vibe — get the perfect date idea instantly.",
    category: "Love & Relationships",
    path: "/date-idea-generator",
    icon: "CalendarHeart",
    color: "bg-rose-600",
  },
  {
    id: "couple-challenge-ideas",
    name: "Couple Challenge Ideas",
    description: "Random challenges to strengthen your bond — including a spicy 🌶️ mode.",
    category: "Love & Relationships",
    path: "/couple-challenge-ideas",
    icon: "Swords",
    color: "bg-purple-500",
  },
  {
    id: "red-flag-detector",
    name: "Red Flag Detector",
    description: "Describe a situation — we'll flag the warning signs for you.",
    category: "Love & Relationships",
    path: "/red-flag-detector",
    icon: "Flag",
    color: "bg-red-500",
  },
  {
    id: "username-generator",
    name: "Username Generator",
    description: "Generate unique, style-matched usernames for any platform.",
    category: "Creative",
    path: "/username-generator",
    icon: "AtSign",
    color: "bg-violet-500",
  },
  {
    id: "tattoo-idea-generator",
    name: "Tattoo Idea Generator",
    description: "Pick style and placement — get a unique tattoo concept with pro tips.",
    category: "Creative",
    path: "/tattoo-idea-generator",
    icon: "Pen",
    color: "bg-slate-600",
  },
  {
    id: "how-rare-are-you",
    name: "How Rare Are You?",
    description: "Select your rare traits and find out your statistical rarity percentage.",
    category: "Creative",
    path: "/how-rare-are-you",
    icon: "Gem",
    color: "bg-violet-600",
  },
  {
    id: "dream-interpreter",
    name: "Dream Interpreter",
    description: "Describe your dream and discover what your subconscious might be saying.",
    category: "Creative",
    path: "/dream-interpreter",
    icon: "Moon",
    color: "bg-indigo-600",
  },
];

export const CATEGORIES = ["Decision Making", "Fun & Social", "Student Tools", "Productivity", "Love & Relationships", "Creative"];

export const GEN_Z_SLANG = [
  { term: "no cap", definition: "Telling the truth; not lying.", example: "That test was impossible, no cap." },
  { term: "rizz", definition: "Charisma or the ability to attract a romantic partner.", example: "He has unspoken rizz." },
  { term: "slay", definition: "To do something exceptionally well.", example: "You look amazing, slay!" },
  { term: "bussin", definition: "Extremely good (often referring to food).", example: "This pizza is bussin." },
  { term: "based", definition: "Being yourself and not caring what others think.", example: "That's a very based opinion." },
  { term: "vibe check", definition: "Assessing someone's mood or energy.", example: "I had to give him a vibe check before inviting him over." },
  { term: "lowkey", definition: "Secretly or somewhat; not wanting to draw attention to it.", example: "I lowkey want to stay home tonight." },
  { term: "highkey", definition: "Very much so; openly and proudly.", example: "I highkey love this song." },
  { term: "situationship", definition: "A romantic relationship that is undefined or uncommitted.", example: "They've been in a situationship for six months." },
  { term: "delulu", definition: "Short for delusional.", example: "She's totally delulu if she thinks he's going to text back." },
  { term: "understood the assignment", definition: "To do exactly what was expected, often exceeding expectations.", example: "The costume designer completely understood the assignment." },
  { term: "main character energy", definition: "Acting like the star of the show; confident and dramatic.", example: "Walking into the party with main character energy." },
  { term: "beige flag", definition: "A trait that is neither good nor bad, just a bit odd or boring.", example: "His beige flag is that he only eats plain toast." },
  { term: "it's giving", definition: "Emanating a certain vibe or style.", example: "It's giving 90s nostalgia." },
  { term: "rent free", definition: "When you can't stop thinking about someone or something.", example: "That embarrassing moment lives in my head rent free." },
  { term: "touch grass", definition: "Advice to get off the internet and go outside.", example: "You've been arguing on Twitter all day, go touch grass." },
  { term: "IYKYK", definition: "If you know, you know.", example: "That one scene in the movie... IYKYK." },
  { term: "glow up", definition: "A major transformation, usually in appearance or confidence.", example: "She had a huge glow up over the summer." },
  { term: "W", definition: "A win; a success.", example: "Getting that job offer is a massive W." },
  { term: "L", definition: "A loss; a failure.", example: "Taking a big L on that math exam." },
  { term: "goated", definition: "Greatest of all time.", example: "This new album is goated." },
  { term: "NPC", definition: "Non-playable character; someone who lacks independent thought.", example: "He just repeats what everyone else says, total NPC behavior." },
  { term: "mid", definition: "Mediocre; average or unimpressive.", example: "To be honest, the sequel was pretty mid." },
  { term: "ate", definition: "Did something perfectly.", example: "She wore that dress and she absolutely ate." },
  { term: "periodt", definition: "End of discussion.", example: "That's the best flavor, periodt." },
  { term: "cheugy", definition: "Outdated, trying too hard, or uncool.", example: "Using minion memes is so cheugy." },
  { term: "sus", definition: "Suspicious.", example: "He was acting really sus yesterday." },
  { term: "ghosting", definition: "Cutting off all communication suddenly and without explanation.", example: "I think I'm getting ghosted." },
  { term: "catch flights not feelings", definition: "Prioritizing travel and experiences over romantic attachments.", example: "This year it's all about catching flights not feelings." },
  { term: "era", definition: "A distinct period in someone's life characterized by a specific focus.", example: "I'm in my villain era." },
  { term: "core", definition: "A suffix used to denote a specific aesthetic.", example: "Her room is totally cottagecore." },
  { term: "aesthetic", definition: "A specific visual style or vibe.", example: "I love the retro aesthetic of this cafe." },
  { term: "vibe", definition: "The atmosphere or feeling of a place or situation.", example: "The party had a really chill vibe." },
  { term: "gaslit", definition: "Manipulated into doubting one's own sanity or reality.", example: "I feel like I'm being gaslit by this timeline." },
  { term: "parasocial", definition: "A one-sided relationship, usually with a celebrity.", example: "People have intense parasocial relationships with streamers." },
  { term: "shadowbanned", definition: "When a user's content is blocked or hidden without their knowledge.", example: "My posts aren't getting likes, I think I'm shadowbanned." },
  { term: "ick", definition: "A sudden feeling of disgust towards someone you were attracted to.", example: "He clapped when the plane landed and it gave me the ick." },
  { term: "that girl", definition: "An archetype of a woman who has her life together, wakes up early, works out, etc.", example: "She's definitely in her 'that girl' phase." },
  { term: "it's not it", definition: "Disapproval of something.", example: "That outfit? Yeah, it's not it." },
  { term: "no thoughts head empty", definition: "Being blissfully unaware or unable to focus.", example: "Staring at the wall... no thoughts head empty." },
  { term: "pick me", definition: "Someone who acts differently to gain attention or validation from the opposite sex.", example: "She's acting like such a pick me." },
  { term: "red flag", definition: "A warning sign of problematic behavior.", example: "Being rude to waiters is a massive red flag." },
  { term: "green flag", definition: "A positive trait that indicates a healthy relationship dynamic.", example: "He listens when you talk, that's a green flag." }
];
